version: "3.9"
services:
  db:
    image: "postgres:15.0-alpine"
    restart: "always"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "parking"
    volumes:
      - "db:/var/lib/postgresql/data"

volumes:
  db:
    driver: local

